.azure/staging-pipeline.yml, .azure/templates/test.yml
Moved conditional trigger for CodeAuditor on pipelines
=> Ca conditional trigger

src/style.css
changed mouse cursor on hover for .button-next.bg-ssw-grey
=> Made disabled button not show clickable

src/style.css
- added word break to avoid horizontal scroll on long links
- made all boxes last paragraph to not have margin bottom (only greybox had it)
=> small improvements to CSS

src/style.css
https://github.com/SSWConsulting/SSW.Rules/issues/221
Used the same styling as links inside rules.
**Figure: Styled links in category intro**
=> 💄  Add styling to category intro links

src/components/dropdown-card/dropdown-card.js, src/components/header/header.js, src/components/signin/signin.js, src/style.css
Issues:
- https://github.com/SSWConsulting/SSW.Rules/issues/261
- https://github.com/SSWConsulting/SSW.Rules/issues/257
Since the dropdown has moved to the right, it doesn't move when the screen size gets small, so I could remove some code that handled the change of position.
=> 💄 Move dropdown avatar

src/components/header/header.js
=> ✨  Add tagline

src/components/header/header.js, src/style.css
issue: https://github.com/SSWConsulting/SSW.Rules/issues/267
Made code block horizontally scrollable
Also made tagline only visible on the home page
=> 💄  Fix overflowing code blocks

src/style.css
issue: https://github.com/SSWConsulting/SSW.Rules/issues/251
=> 💄  Switch font for more consistency

src/components/acknowledgements/acknowledgements.js, src/style.css, src/templates/rule.js
issue: https://github.com/SSWConsulting/SSW.Rules/issues/282
=> 59874 add categories aknowledgment wiki link

src/style.css
issue: https://github.com/SSWConsulting/SSW.Rules/issues/251
=> 💄  Make content fonts same weight

src/style.css, src/templates/category.js
Issue: https://github.com/SSWConsulting/SSW.Rules/issues/268
=> Made category and rule padding responsive

src/style.css
https://github.com/SSWConsulting/SSW.Rules/issues/198 
https://rules.ssw.com.au/do-you-use-underlines-only-on-links
=> Fixed breadcrumbs underlines

src/components/profile-content/profile-content.js, src/components/profile-filter-menu/profile-filter-menu.js, src/components/reaction/reaction.js, src/style.css
Issues:
https://github.com/SSWConsulting/SSW.Rules/issues/295
https://github.com/SSWConsulting/SSW.Rules/issues/250
https://github.com/SSWConsulting/SSW.Rules/issues/255
**Figure: Change "really agree" to "love it!"**
**Figure: Change to Love icon**
=> 💄  Change "really agree" to "love"

src/style.css
removed unnecessary CSS and duplicate statements
=> Trying to simplify the CSS for captions

src/style.css
Made external icon for outside **ssw.com.au** not **rules.ssw.com.au**
=> Fixed external icon NOT link

src/components/profile-content/profile-content.js
issue: https://github.com/SSWConsulting/SSW.Rules/issues/309
=> 💄  Fix spacing on view filter

src/components/profile-content/profile-content.js, src/style.css
issue: https://github.com/SSWConsulting/SSW.Rules/issues/318
=> 💄  Change icon for no rules message

src/components/top-category/top-category.js, src/style.css
=> 60060 fix multi line indent rule list

static/web.config
This reverts commit 62b55e7f1c3cadf50a5726464e8a55ca5262ceed.
=> Revert "Try fix with customErrors mode (#353)"

src/components/reaction/reaction.js
issue: https://github.com/SSWConsulting/SSW.Rules/issues/294
**Figure: After clicking react, you can click again to remove reaction**
=> ✨  Add remove rating feature

src/style.css
Reverts SSWConsulting/SSW.Rules#367
=> Revert "Fix caption semantics"

src/style.css
=> fixed spacing on rule cat area

src/components/side-bar/side-bar.js
Correct link: https://twitter.com/adamcogan
=> fixed link to "Tweet me" - Thanks CodeAuditor!

src/style.css
https://github.com/SSWConsulting/SSW.Rules.Content/issues/101
=> 🐛  Fix images not showing up

src/components/side-bar/side-bar.js
=> from "email us" to "contact us"

src/style.css
**Figure: Broken Acknowledgements**
**Figure: Fixed! 🙂**
=> 🐛  Fix acknowledgements image

src/services/apiService.js
=> 🚑  Fix empty data in CosmosDB

src/pages/404.js, src/style.css
Issue: https://github.com/SSWConsulting/SSW.Rules/issues/345
**Figure: New 404 page**
**Figure: Responisve 404 page**
=> Changes to 404 page

.azure/production-pipelines.yml, .azure/staging-pipeline.yml, .azure/templates/cancelPreviousBuilds.ps1
https://github.com/SSWConsulting/SSW.Rules/issues/388
=> 👷  Added pwsh script to cancel existing builds

.azure/production-pipelines.yml, .azure/staging-pipeline.yml
Reverts SSWConsulting/SSW.Rules#406
=> Revert "👷  Add pwsh script to pipelines"

src/components/profile-filter-menu/profile-filter-menu.js, src/components/reaction/reaction.js, src/services/apiService.js, src/style.css
Added red highlighting on border and icon on reaction tab selection as well as hover (reduced opacity). Changed no way symbol to ban symbol.
=> Added profile reactions red highlighting. Changed no way symbol.

src/style.css
Only blurb had cursor:pointer;
=> Made View mode labels consistent

src/style.css
issue: #250 
**Figure: new icon is used**
=> 💄  Update icon

src/services/apiService.js, src/style.css, src/templates/rule.js
Reverts SSWConsulting/SSW.Rules#427
=> Revert "✨  Add profile link"

gatsby-config.js, package.json, yarn.lock
As per my conversation with Piers, we have investigated exactly what DEV_SSR does and included that information below.
This information came from the offical Gatsby Discord https://gatsby.dev/discord
This should fix the 200 status code on the 404 page.
This is not working in development but a issue to fix this has been created
https://github.com/gatsbyjs/gatsby/issues/30730
This makes it so when you refresh a page, the dev server SSRs (Server-side-reloads)  the page in the same way it does during builds. This is a feature flag as it is a preview feature.
=> 🚩  Enable DEV_SSR feature flag

static/web.config
According to these docs: 
https://techcommunity.microsoft.com/t5/iis-support-blog/issue-iis-logs-200-status-code-instead-of-404/ba-p/297652
https://forums.asp.net/t/2079017.aspx?200+status+code+returned+for+IIS+404+error+page
This change should make IIS respond with 404 errors.
=> 🔧  Change response mode

static/web.config
=> 60689 fix 200 code on 404 page

gatsby-config.js, static/web.config
This fix just broke the 404 page. Undoing the changes.
=> Revert 442 60689 fix 200 code on 404 page

static/web.config
issue: https://github.com/SSWConsulting/SSW.Rules/issues/423
These changes will make the 404 page use the 200 status code.
=> 🔧  Fix 404 page with status code 200

static/web.config
As per my conversation with Matt, we might need to configure IIS to handle .yml files
https://serverfault.com/a/108470
=> 🔧  Add mime mapping for yml

src/style.css
issue #480
**Figure: Bullet points on categories**
=> 💄 Add bullet points to categories

src/style.css, src/templates/rule.js
issue https://github.com/SSWConsulting/SSW.Rules/issues/479
**Figure: Removed created date and added 'See history' link**
=> Remove created date and add 'see history' link

src/style.css
issue #485 
**Figure: Old table style**
**Figure: New table styles**
=> Add styling for tables

src/templates/rule.js
issue https://github.com/SSWConsulting/SSW.Rules/issues/496
=> Make next and previous buttons always show up

src/style.css
Removed some CSS that was making images really big
issue https://github.com/SSWConsulting/SSW.Rules/issues/433
**Figure: Bad**
**Figure: Good**
=> Fix large images

src/components/acknowledgements/acknowledgements.js
=> Fix images for authors

src/templates/rule.js
issue https://github.com/SSWConsulting/SSW.Rules/issues/496
=> Add tracking to next and previous buttons

static/admin/config.yml
Followed https://github.com/tylergaw/netlify-cms-github-oauth-provider-server-example to try setup custom auth.
If this works we could implement something similar with Azure Functions
=> Test custom auth server

.azure/production-pipelines.yml, .azure/staging-pipeline.yml
issue https://github.com/SSWConsulting/SSW.Rules/issues/428
=> Move CodeAuditor trigger to production

src/style.css
=> 🐛  Fix figure and image spacing

lib/ssw.megamenu/dropdown-item/dropdown-item.js, lib/ssw.megamenu/dropdown-item/dropdown-item.module.css
=> Fix broken MegaMenu

src/cms/cms.js, static/admin/config.yml
Don't merge until https://github.com/SSWConsulting/SSW.Rules.Functions/pull/26 is merged
=> Connect Netlify CMS to authentication functions

gatsby-config.js, src/style.css
=> Increase image size limit

src/components/header/header.js
Temporarily switched the edit button back to GitHub, so we can deploy Netlify
=> Switch edit button back to GitHub

static/admin/config.yml
=> Add logo and URL

src/cms/previewTemplate.js, src/style.css, static/admin/config.yml
For issue: https://github.com/SSWConsulting/SSW.Rules/issues/466
Fixed the figure statements, good/bad icons and YouTube embeds
=> Fix custom previews

src/components/breadcrumb/breadcrumb.js, src/components/header/header.js
Fixed issue #199 linked to [PBI 59378](https://dev.azure.com/ssw/SSW.Rules/_workitems/edit/59378).
Changed breadcrumb styling to make all links and headings more consistent.
**Figure: Old breadcrumb styling**
**Figure: New breadcrumb styling**
=> 59378 - Changed styling of breadcrumbs for consistency

static/web.config
issue #523
Used the solution here https://ruslany.net/2009/04/10-url-rewriting-tips-and-tricks/#trailing-slash
The new rule will remove the trailing slash from all URLs so the redirects will work
=> 🔧  Add rule to remove slash

src/components/footer/footer.js, src/style.css
Closes issue #596 and PBI 62695.
Added social media icons featured on the Consulting website into the footer of Rules.
**Figure: Social media icons in footer. QR code appears when hovering over WeChat icon.**
=> 💄 Add social media icons to footer

src/style.css
=> improved padding for email templates

src/components/header/header.js
Closes issue #611 and PBI 62915.
Added a 'New Rule' button to the header of SSW Rules.
**Figure: New Rule button in the header.**
=> 💄 Add New Rule button to header

src/components/bookmark/bookmark.js, src/components/footer/footer.js, src/components/header/header.js, src/style.css, src/templates/rule.js
Closes issue #618 and PBI 63201.
Changed the look of buttons as per suggestions in the issue.
**Figure: Buttons are different colour, some have different icons**
**Figure: Buttons are different colour and footer link has changed**
**Figure: 'Easy to maintain' link moved to Wiki**
=> Improve button UI

src/pages/index.js, src/style.css
=> 💄 Add link to old rules

src/style.css, src/templates/category.js
The category headings were incorrectly styled in staging. I have corrected this.
=> Fixed styling of category headings

src/components/footer/footer.js
to be consistent with sugarlearning.com
=> updated feedback label

.azure/codeauditor-pipeline.yml
Updated the pipeline for scheduled CodeAuditor checks.
- Removed branch trigger
- Increased frequency for easy testing
=> CodeAuditor pipeline v2

src/style.css
To fix https://github.com/SSWConsulting/SSW.Rules/issues/681
=> Increased margin-bottom on headings

src/style.css
Updated styling around the bookmark and edit buttons
=> Updated bookmark button styles

src/templates/rule.js
Removing the unnecessary <P> tag
=> 🔥 #717 removed the p tag

src/components/side-bar/side-bar.js
CC: @adamcogan @pierssinclairssw @theixdev @JackDevAU 
Updated the sidebar layout after consultation with designers.
=> Adjusted Sidebar layout

src/style.css
Found some bugs when reviewing commits before deployment. 
- Fixes the css issues
=> 🐛 Fixed rule tooltips css

.github/ISSUE_TEMPLATE/0-feature.md, .github/ISSUE_TEMPLATE/1-bug.md, .github/ISSUE_TEMPLATE/2-docs.md, .github/ISSUE_TEMPLATE/3-refactor.md, .github/ISSUE_TEMPLATE/4-devops.md, .github/ISSUE_TEMPLATE/config.yml, .github/pull_request_template.md
As we wanted to add GitHub Issues templates for users to easily report bugs or suggestions, they should be added to this repository.
Changes:
- Added the GitHub Issues templates from https://github.com/SSWConsulting/SSW.GitHub.Template.
=> 🔧 Added GitHub Issues templates

gatsby-config.js, src/style.css
- Fixing underline issue raised by @tiagov8 
- Fixing figure icon issue raised by @tkapa 
**Figure: The underline issue** 
**Figure: The "good" and "bad" figure text and icons issue**
=> 🐛 Fix Figure + ul underlines

gatsby-config.js
Fix figure text not showing properly under relative images
=> 🐛 figures are now back in town

README.md
Cc: @JackDevAU @christianmorfordwaitessw @bradystroud 
I was blocked for an hour trying to get my local build to work following the readme. Running yarn build before running yarn develop had me running into issues when running the website locally.
Changes:
- Remove the line from Christian
> 2. Run *yarn build* (.env.production is required for this step)
=> 📝 Update README.md for running in development

.azure/scripts/get-rule-history.ps1, .azure/scripts/update-rule-history.ps1, .azure/templates/build.yml, .azure/update-rule-history.yml
- Added PowerShell scripts to generate rule history data
- Added pipeline to generate rule history data
- Updated build pipeline to pull down history.json
=> Azure pipelines rule history

package.json, src/style.css, yarn.lock
https://github.com/SSWConsulting/SSW.Rules/issues/731
Updated NPM version of Widget.  Applied additional CSS to stop undesired results like underlining of anchor tags on hover.
=> 💄widget style update

package.json, src/style.css, yarn.lock
Reverts SSWConsulting/SSW.Rules#742
=> Revert "💄widget style update"

.azure/scripts/get-rule-history.ps1, .azure/scripts/update-rule-history.ps1
#459 CI/CD - History.json update process should be moved into the build pipeline
- Fixed the PowerShell scripts to exit on error preventing the sync hash to be updated on failure
=> 61012 fix pwsh scripts

.github/pull_request_template.md
#716 
- Add a task to the PR templates to make sure everyone who is using VS Code has the recommended plugins installed before pushing
=> 📝 Update PR template

.azure/templates/build.yml
=> Add yarn cache flag

src/style.css
Not sure what this is
https://github.com/SSWConsulting/SSW.Rules/issues/763
Added ":first-child" to table on mobile media parameter
Included in the issue
=> fixed email template for mobile

gatsby-config.js
#701 [#1801](https://github.com/SSWConsulting/SSW.Rules.Content/issues/1801)
- More headers now have anchor tags - add h2 & h4
- Changed the link Icon colour to cc4141
=> ✨ Update linkable headers

static/web.config
#745
- Add history.json endpoint for rules
=> 🔧 Make json endpoints accessible

static/web.config
Reverts SSWConsulting/SSW.Rules#772
=> Revert "🔧 Make json endpoints accessible"

src/components/footer/footer.js
Updated to the current friendly link
=> fixed link to T&C

src/api/historyFeed.js
=> Testing API endpoint

src/components/footer/footer.js
reordering social icons - Marketing team request
=> reordering social icons - Marketing team request

src/components/breadcrumb/breadcrumb.css, src/components/breadcrumb/breadcrumb.js, src/style.css
https://github.com/SSWConsulting/SSW.Rules/issues/635
- Updated CSS to use Tailwindcss
- Remove html scaffolding 
- Remove commented out code in `style.css`
Figure: Normal view
Figure: Mobile view
=> #635 fix breadcrumb

src/components/topcategory-header/topcategory-header.js, src/pages/archived.js, src/style.css
https://github.com/SSWConsulting/SSW.Rules/issues/761
On the Archive view
1. Removed brackets from rule counts
2. Removed numbering from categories 
3. Made Categories bold
4. Numbered Rules
=> ✨ Improve Archived Rules view

.azure/scripts/update-rule-history.ps1
Reverts SSWConsulting/SSW.Rules#793
Due to pipeline errors
=> Revert "Adding GitHub username to history json"

_docs/Alternative-Solutions-Considered.md, _docs/Business.md, _docs/Definition-of-Done.md, _docs/Definition-of-Ready.md, _docs/Instructions-Compile.md, _docs/Instructions-Deployment.md, _docs/Technologies-and-Architecture.md
As per my conversation with @adamcogan,
I've created the files for the 8 important documents in the _docs folder as according to the [Do you make awesome documentation? rule](https://www.ssw.com.au/rules/awesome-documentation)
=> 📝Documentation - Create the 8 important docs WIP

src/components/side-bar/side-bar.js, src/components/top-category/top-category.js, src/pages/index.js, src/style.css
https://github.com/SSWConsulting/SSW.Rules/issues/770
1. Fixed `<h4>` margin that was being overridden
2. Changed "please contact us"  to be "suggest an edit" with appropriate link
3. Moved the "HELP AND IMPROVE" heading to be inside the testimonial div
4. Moved Adams photo and name to be below the quotation
5. Added a closing quote mark at the end of quotation
6. Added a link to SSW.People from Adam's name
=> 770 sidebar improvements

.vscode/settings.json, gatsby-config.js, package.json, yarn.lock
Installed https://www.gatsbyjs.com/plugins/gatsby-plugin-google-gtag/
=> 📈 Add Google Analytics tag

src/style.css
Closes #687  UI - No spacing between rules in category list
- Fixed spacing between rule titles in category list
- Fixed Acknowledgement alignment if info buttons
- Fixed Rates title alignment
Changes spacing of rule titles from
To
=> Fixed alignments and spacing

_docs/Instructions-Deployment.md
=> 📝 Add deployment instructions

src/components/side-bar/side-bar.js
**Figure: Updated sidebar quote and header text**
=> Updated side bar text and quote

src/cms/config.js
=> 💄 Change label for rule Acknowledgements

src/components/side-bar/side-bar.js
Added link to Adam's twitter + mentioned 'SSW Rules' in the quote
=> Update side-bar.js - link to twitter + mention 'SSW Rules'

.azure/templates/build.yml
=> Add step to increase limit

.azure/templates/build.yml
Reverts SSWConsulting/SSW.Rules#827
This change only made the failure slower
=> Revert "Add step to increase limit"

src/components/side-bar/side-bar.js
=> from 25 to 30 years of experience

src/style.css
#848 
Let me know if you want to change the icons.
Here is the library https://fontawesome.com/v4/icons/
=> 💄  Add icons to file links

src/style.css
- Making icons red
- Merging some CSS to avoid repetition
=> making file icons indicator red

src/style.css
As per my conversation with Adam, each icon now will have a correspondent color
=> Made icons colors match their software

src/style.css
=> Making images be full width + reduce padding

gatsby-config.js, src/style.css
=> ✨ Add no-border option

package.json, yarn.lock
Fixes double slash in widget URLs
=> 📦  Update widget package

src/components/breadcrumb/breadcrumb.js
=> 💄  Fix mobile overflow

.gitignore, src/style.css
fixes youtube icon on all links containing youtube
=> 🐛  Fix rules with youtube in uri showing logo

gatsby-node.js, src/components/acknowledgements/acknowledgements.js, src/templates/rule.js
=> ✨  Allow no image 🫠

.github/workflows/codeauditor-test.yml
Runs at 12pm tuesday Brisbane time (before sprint review)
=> ✅ Update schedule trigger

src/templates/rule.js
https://www.ssw.com.au/rules/how-to-capitalize-titles
=> Fixed capitalization

README.md
=> 📝 Add GitMoji badge

.vscode/settings.json, src/templates/category.js, src/templates/rule.js
=> 📈 Edit buttons tracking

src/style.css
- Fix positioning of good/bad/ok icons. E.g.: https://www.ssw.com.au/rules/appointments-do-you-explain-why-youve-deleted-or-modified-an-appointment
- Improve consistency between greyboxes and other custom boxes look and feel. E.g. https://www.ssw.com.au/rules/rule#boxes
=> Improve CSS syntax

src/pages/404.js
the 404 text is being updated in people and website, updating rules for consistency.
404 pages have inconsistent text
updating the grey box text to be consistent with updated text on people 404 page and website 404 page.
=> Updating 404 txt for consistency

README.md
=> 📝 Improve F5 docs

src/components/side-bar/side-bar.js
as per CodeAuditor
...+ removed unnecessary full stop
=> Removed slash at the end of link

src/components/footer/footer.js
#920
Updated the url to use https
=> 920 - 🐛 Change http to https

src/components/top-category/top-category.js, src/pages/archived.js, src/pages/index.js, src/templates/category.js
- Categories can now be archived
- Archived categories don't show on the homepage
- Archived categories are shown within the archived rules page indicated by the archived icon
- Categories can now be clicked from the archived rules page
=> 579 archive categories

package.json, src/components/breadcrumb/breadcrumb.js, src/pages/index.js, src/pages/orphaned.js, yarn.lock
=> 924 orphaned pages list

src/components/filter/filter.js, src/pages/index.js
- Moved "All rules" button to the top of the page
- Added "Categories" header
- Changed filter option "Date Created" to "Recently Added"
- Changed filter option "Date Edited" to "Recently Updated"
=> improved latest rules experience

src/components/header/header.js, src/components/tooltip/tooltip.js, src/pages/orphaned.js, src/style.css, src/templates/category.js, tailwind.config.js
This is to solve the issue on https://github.com/SSWConsulting/SSW.Rules/issues/900
- Added tooltip component
- Added tooltip to the "+" - "Add new rule"
- Added tooltip to the "?" - "How to edit rules"
- Fixed style problem related to "Edit in GitHub"
=> 💄900 - Add tooltips on buttons

src/components/header/header.js
This is to solve the issue on https://github.com/SSWConsulting/SSW.Rules/issues/811
Removed link on "Rules" header
=> 🐛 811 - Remove link on "Rules" header

src/components/bookmark/bookmark.js, src/pages/orphaned.js, src/style.css, src/templates/category.js, src/templates/rule.js, tailwind.config.js
This is to solve the issue on https://github.com/SSWConsulting/SSW.Rules/issues/833
- Added style for inactive buttons
**Figure: inactive button**
=> 💄833 - Update button style

src/pages/all-rules.js
Replaced old filter options that were missed when updating to new names
=> Replaced old filter options with new ones

src/components/breadcrumb/breadcrumb.js, src/components/footer/footer.js, src/pages/index.js, tailwind.config.js
=> 💄 Change dotted links to solid

site-config.js
Adding `www` to cannonical URLs, as per Craig's suggestion
fixes #960 and #959
=> 🔍  Fix cannonical urls

src/components/breadcrumb/breadcrumb.js
closes #392 
- Changed current rule to "This rule"
- Changed current category to "This category"
- Removed "Rules to" suffix
=> Shortened breadcrumbs

src/components/breadcrumb/breadcrumb.js, src/pages/index.js
This is to solve https://github.com/SSWConsulting/SSW.Rules/issues/962
- Added styles that make the link underline red on hover
=> 💄962 - Make link underline red

src/components/floating-bubble/floating-bubble.js, src/components/layout/layout.js
This is to add the feature on https://github.com/SSWConsulting/SSW.Rules/issues/963
- Created a bubble component that redirects to https://rulesgpt.ssw.com.au/ when clicked on
- Added the component to the layout so that it appears on every page
On mobile:
=> ✨ 963 - Add floating bubble that jumps to RulesGPT

package.json, scripts/updateRelativePath.js, site-config.js, src/components/breadcrumb/breadcrumb.js
- Links now relative
- Added new 'siteUrlRelative' attribute in config file
closes #939
=> Updated breadcrumbs

src/components/latest-rules-content/latestRulesContent.js, src/pages/index.js, src/pages/latest-rules.js
=> Renamed all occurances of all rules and variations to latest rules

src/components/header/header.js
To solve the new task on https://github.com/SSWConsulting/SSW.Rules/issues/963
Change I made:
- Add red hover effect on RulesGPT button
=> ✨963 - Add hover effect on RulesGPT

src/style.css
Fix https://github.com/SSWConsulting/SSW.Rules/issues/864
- Removed external icon from YouTube links
=> 💄Remove external icon from YouTube links

src/style.css, src/templates/rule.js
This is to solve the issue on https://github.com/SSWConsulting/SSW.Rules/issues/933
- Add "Archived" tag for archived rule
- Delete css class, replace it with tailwind class
=> ✨ Add tag for archived rule in category section

src/cms/config.js
Solve https://github.com/SSWConsulting/SSW.Rules/issues/875
- Enabled the GraphQL API for the Github backend
**Most of the requests are made via the GraphQL API instead of the REST API on CMS**
=> ✨ Enable GraphQL Api for Netlify CMS

src/pages/index.js
Solve problem on https://github.com/SSWConsulting/SSW.Rules/issues/978
Changes:
- Fixed hover style issue with "Latest Rule" link
=> 💄 Fix hover effect issue for Latest Rules Link

gatsby-node.js, src/components/breadcrumb/breadcrumb.js, src/pages/latest-rules.js
=> Fixed Latest Rules breadcrumb showing "This rule"

src/pages/index.js, src/pages/latest-rules.js
Defaulted the amount of rules shown on the latest rules page from 10 to 50
Fixes #995
=> defaulted rules shown to 50

src/components/layout/layout.js
Updated title tag from "SSW.Rules | Secret ingredients to quality software" to "SSW.Rules | Latest Rules"
Fixes #998
=> Updated title

src/components/header/header.js, src/components/tooltip/tooltip.js
Fixes #1000 
- Make the "RulesGPT" tooltip appear automatically after 3s, and disappear after 15s.
- Tooltip - Change text to “✨ Try out RulesGPT”
- New rule button - Change to “Create a SSW Rule”
=> 💄Tooltip show automatically

package.json, src/components/layout/layout.js, yarn.lock
Fixes #936 
- Changed the code of the MegaMenu so that the images will be displayed only after they have finished loading
- Upgraded the MegaMenu package
- Added the MenuBar component as recommended
=> 🐛 Fix broken images on the mega menu

src/style.css
Fixes #1006 
- Add icon on the left of the google map link
=> 💄 Add icon for google link

src/components/acknowledgements/acknowledgements.js, src/templates/rule.js
Fixes #1008 
- Rewrite function to handle Acknowledgements images better
- Log a warning when there is no title on the image
=> ♻️ Handle empty title in Acknowledgements

src/components/header/header.js
Fixes #1000 
- Help button - Change text to “SSW Rules wiki”
- RulesGPT button - Add Application Insights to log the number of clicks
=> 💄 RulesGPT link improvements

src/components/heading/heading.js
Fixes #979 
- Added a loading spinner
=> ✨ Add loading indicator

src/components/header/header.js
Fixes https://github.com/SSWConsulting/SSW.Rules/issues/1000#issuecomment-1590632336
- removed the emoji on the tooltip
=> 💄Remove tooltip emoji

src/components/rule-side-bar/rule-side-bar.js, src/components/sidebar-categories/sidebar-categories.js, tailwind.config.js
Fixes #800 
- Added display condition for "Related Rules"
- Removed padding in Category section
=> 💄New Sidebar style improvement

src/components/breadcrumb/breadcrumb.js, src/components/sidebar-categories/sidebar-categories.js
=> Added regex to remove "Better" from breadcrumb categories

src/components/rule-side-bar/rule-side-bar.js, tailwind.config.js
Fixes https://github.com/SSWConsulting/SSW.Rules/issues/800#issuecomment-1597588979
Changes:
- Added top bottom padding to the sidebar
- Updated mask-image style
=> 💄Update sidebar mask style

src/components/footer/footer.js, src/style.css
CC: @tiagov8 @2fernandez @jaydenalchin 
As per my conversation with @jaydenalchin I have updated icons in footer:
- Removed WeChat
- Added TikTok
- Removed icon backgrounds
- Test pass from
Relates to #904
=> Updated icons in footer

src/helpers/historyFeedGenerator.js
Fixes #1023 
Changes:
- Removed limit of graphql query
- Renamed the history-feed.json file
=> ♻️ Remove history feed limit

src/components/breadcrumb/breadcrumb.js, src/components/sidebar-categories/sidebar-categories.js, src/templates/category.js
Trimmed leading and trailing spaces from breadcrumb
Related #1025
=> trimmed leading and trailing spaces from breadcrumb

package.json, src/components/side-bar/side-bar.js, yarn.lock
Relates to https://github.com/SSWConsulting/SSW.Rules/issues/786
Changes:
- Updated the widget
=> 📦 Update widget package

gatsby-config.js
Fixes https://github.com/SSWConsulting/SSW.Rules.Content/issues/5772
Changes:
- Update config for "gatsby-remark-copy-linked-files" so the image file can be generated in the public folder
=> 🔧Update Gatsby Plugin Config

.github/workflows/codeauditor-test.yml
Relates to https://github.com/SSWConsulting/SSW.CodeAuditor/issues/455
=> Updated CodeAuditor scan command line

src/components/profile-content/profile-content.js, src/components/radio-button/radio-button.js, src/pages/orphaned.js, src/style.css, src/templates/category.js, tailwind.config.js
Relates to #822 
Changes:
- Display the button after the page is loaded
- Use new Radio Button component to avoid duplicate code
=> 🐛Updated View Button

package.json, yarn.lock
Relates to https://github.com/SSWConsulting/SSW.Rules.Widget/issues/33
=> 📦Update Widget Package

tailwind.config.js
Relates to https://github.com/SSWConsulting/SSW.Rules/issues/822
Changes:
- Updated the tailwind.config.js so that the static images will be shown in production.
=> 🐛 Add Path Prefix for Images

src/components/breadcrumb/breadcrumb.js, src/components/search-bar/search-bar.js, src/pages/latest-rules.js, src/pages/search.js
Relates to https://github.com/SSWConsulting/SSW.Rules/issues/1033
As per my conversation with @bradystroud , add a new page for the search feature
Changes:
- Added search page
- Removed search code in the latest-rule page
=> 🔎 Add Search Page

src/components/layout/layout.js
Relates to #386 
Changes:
- Updated the style of the container div in mobile screen
=> 💄Fix Fitting on Mobile View

src/components/breadcrumb/breadcrumb.js
=> Updated orphaned breadcrumb styling

src/components/footer/footer.js
Updated link to save redirecting
=> Update footer.js link to T&C

src/pages/index.js
=> Fix Orphaned/Archived/Unmigrated link underlines

.azure/scripts/create-commits-history.ps1, src/pages/latest-rules.js, static/commits.json
Relates to https://github.com/SSWConsulting/SSW.Rules.Widget/issues/39
Changes:
- Modified the psl script to get necessary data (rule's title and uri) for Rules.Widget
- Updated static/commits.json for the development environment
**Figure: new data structure in commits.json**
=> 🔨 PowerShell Script - Get rules data for Widget

src/pages/index.js, src/pages/orphaned.js, src/pages/search.js, src/pages/user-rules.js, src/style.css
=> 💄 Fix Category Title Style

src/style.css, src/templates/category.js, tailwind.config.js
To action this https://github.com/SSWConsulting/SSW.Rules/issues/899
=> 💄 Improving headings and images

src/components/contact-form/contact-form.js
=> 🐛 Edit form payload to match new endpoint

src/style.css
cc @Freego1783 @adamcogan @JeanThirion @PothieuG @Khaled-Albahsh @SofieHong 
To fix this:
From thread: **Re: SSW Rules - Suggestion - Website Chatbot**
=> CSS - Added "word-break:initial" to tables

src/components/footer/footer.js
=> update deployment link

src/components/contact-form/contact-form.js
=> 📝 Add Doc Reference For Creating Lead

package.json, yarn.lock
=> 📦 Upgrade SSW.Megamenu to 3.2.2

package.json, yarn.lock
=> Upgraded menu to 3.2.3

src/helpers/algolia-queries.js
=> Fix algolia build issue

scripts/favicons.js
Relates to #1096 
Changes made:
- update favicon path from `/icons/` to `/rules/icons/`
=> 🐛 Fix Favicon Path

gatsby-node.js
=> 🐛 Add Diagram Type

src/components/footer/footer.js
Related to https://github.com/SSWConsulting/SSW.Website/pull/1452
=> Made copyright info standard

src/components/heading/heading.js, src/components/latest-rules-content/latestRulesContent.js
Relates to #997 
Changes:
- Fixed the weird column style
**Figure: Before update**
**Figure: After update**
=> 💄 Update "Added By" Column Style

gatsby-node.js, src/components/breadcrumb/breadcrumb.js, src/components/heading/heading.js, src/components/latest-rules-content/latestRulesContent.js, src/pages/archived.js, src/pages/latest-rules.js, src/pages/search.js, src/pages/user-rules.js, src/pages/user/index.js, src/style.css
Relates to https://github.com/SSWConsulting/SSW.Rules/issues/1046#issuecomment-1739814861
Changes made:
- Updated page title
- Replaced pagination with "load more"
- Changed the url to `https://ssw.com.au/rules/user/?author={github login name}`
- Added "ago" after the timestamp
- Added another list to show acknowledgement
**Figure: is the title `{{ USER NAME }}'s Acknowledged Rules` good enough? 🤔**
=> ♻️ Improve User Filter

package.json, yarn.lock
Relates to [#45](https://github.com/SSWConsulting/SSW.Rules.Widget/issues/45)
=> updated widget

.gitignore, gatsby-config.js, package.json, yarn.lock
=> added gatsby package to support mermaid diagrams

src/components/side-bar/side-bar.js
=> 💔Break the widget

src/components/profile-content/profile-content.js, src/services/apiService.js
=> 🐛 Fix profile page

src/components/contact-info/contact-info.js
=> added link tag to phone number

_docs/Definition-of-Done.md
=> 📝Definition of Done

src/components/layout/layout.js
Fixes a spam of warnings with the auth0 package.
=> 🩹 fix auth0 warning

.yarnrc.yml, gatsby-node.js, src/components/footer/footer.js, src/components/head/head.js, src/components/header/header.js, src/components/side-bar/side-bar.js, src/pages/404.js, src/pages/orphaned.js, src/templates/category.js, src/templates/rule.js
=> remove absolute links

.azure/templates/build.yml
=> fixed env variable

.azure/scripts/update-latest-rules.ps1, .azure/update-rule-history.yml
Relates to #1152 
- Removes UpdateLatestRules from the pipeline as there is an issue. 
- Updates latest rules .ps1 script
=> Removes updating the latest rules for the moment 

.azure/update-rule-history.yml
=> uncommented script step

.azure/scripts/update-latest-rules.ps1
=> Remove /api from url

src/style.css
Jack and I noticed the new black X button had a blue background colour that made it ugly.
We pair programmed and removed it
=> 💄 Remove background color from Twitter hashtag button

src/style.css
cc @adamcogan 
Relates to https://github.com/SSWConsulting/SSW.Rules/issues/1199
=> Widen mobile display so that we have more words on the same line

package.json, src/components/side-bar/side-bar.js, yarn.lock
Changes:
- Updated Widget version
- Temporarily disabled it until the Azure function is deployed to production to prevent the Rules from crashing
=> ⏸️ Temporarily Disable Widget

src/components/side-bar/side-bar.js
Relates to Email: Rules Widget - Temporarily being taken offline
=> ▶️ Add Widget Back

.github/workflows/playwright.yml, .gitignore, package.json, playwright.config.js, src/components/side-bar/side-bar.js, tests/megadata.spec.js, yarn.lock
Relates to #1178 
Added Playwright for UI testing, working as below:
- Check whether the https://ssw.com.au/rules/history.json file exists
- Go to latest rules page, randomly select a rule, navigate to that rule's page and check if it has metadata
=> ✨ Test - Add Playwright to Test Metadata 

src/services/apiService.js
Relates to #1185 
Fixed the GetUser function so it can display the user's comment information normally
=> 🐛 Fix GetUser Function

site-config.js, src/components/head/head.js
Relates to #1159
Change:
- Updated page title to follow the best practice
=> Updated Page Title

src/components/head/head.js
Relates to #1159 
Making the new title work in staging/production
=> Update Homepage Title

.azure/scripts/update-rule-history.ps1
Change:
- Removed double quote in the `$startCommitHash`
=> 🐛 Fix UpdateRulesHistory Pipeline Error

src/components/search-bar/search-bar.js, src/pages/index.js, src/pages/latest-rules.js, src/pages/search.js
- Fixed search bar styling to be full width
- Added search bar to homepage
As per my conversation with @jaydenalchin, here is the new design for the search bar
Relates to #1250
=> Refined search bar styling 

src/components/search-bar/search-bar.js
=> Homepage search bar now redirects using Gatsby navigate.

src/components/header/header.js, src/components/search-bar/search-bar.js
Fixes bug introduced in https://github.com/SSWConsulting/SSW.Rules/pull/1269
=> fixed path redirect

src/components/latest-rules-content/latestRulesContent.js, src/pages/user/index.js
Relates to https://github.com/SSWConsulting/SSW.Rules/issues/1264
Changes:
- Replaced 'ø' with 'oe' to fix the empty acknowledged rules issue
=> User Page - Converting the Character 'ø' to 'oe'

.github/workflows/template-build.yml, .github/workflows/template-deploy.yml, infra/main.bicep
Attempt to fix deployment
Relates to #1292
=> Fix deployment to storage account

.github/dependabot.yml, .github/workflows/playwright.yml, .github/workflows/production.yml, .github/workflows/staging.yml, .github/workflows/template-build.yml, .github/workflows/template-deploy.yml, build-scripts/create-commits-history.ps1, build-scripts/get-rule-history.ps1, build-scripts/update-latest-rules.ps1, build-scripts/update-rule-history.ps1
Improves file copy speed to blob storage
Adds ability to specify branch name as a param when using worflow_dispatch
Separates commit/history.json file creation from build process - in case there is a build issue and you need to re-run, you'll have to redo less work
Relates to #1302
Check https://github.com/SSWConsulting/SSW.Rules/actions/runs/8814651672 for a sample build
=> Improve upload speed

.github/workflows/template-build.yml, src/components/footer/footer.js
Adds link to GitHub in the footer
Adds content repo info that was used in build
Relates to #1292
=> chore: Record the latest SHA for the content repo and update deployment URL in footer

src/templates/category.js
Relates to #1286 
Remember users view mode by adding sessionStorage
=> ✨ Categories - Remember view mode

README.md
Relates to #https://github.com/SSWConsulting/SSW.Rules/issues/1301
=> Update README.md - Adds new staging url 

.github/workflows/build-deploy-production.yml, .github/workflows/update-rules-history.yml
Migrate UpdateRulesHistory pipeline from azure to github for synchronizing rules' history
=> Migrate UpdateRulesHistory Pipeline from Azure to GitHub

.github/workflows/template-build.yml
Fixing 401 issue when clicking on a person's name in the latest rules table
=> Update GitHub PAT Secrets to Use Rules.Content Token

src/components/latest-rules-content/latestRulesContent.js
The link of the "updated by" list in the latest rules page is wrong, fix it.
Relates to #1160
=> 🐛Update the link of the "updated by" list in latest rules page.

infra/main.bicep
Relates to https://github.com/SSWConsulting/SSW.Rules/issues/1335
Include the CORS Rules config in the bicep to fix the issue below:
=> Add CORS Rules to Bicep

src/helpers/wrapPageElement.js
Relates to #1333 
Fixed the titles of these pages:
- Orphaned Rules
- Archived Rules
- Profile
=> 🔎 SEO - Fix Page Titles

src/pages/user/index.js
Relates to #1351 
User page - added a link to people profile
=> 💄 User Page - Add Link to People Profile

.github/workflows/template-build.yml
=> Reverse logic

.azure/scripts/update-rule-history.ps1, .github/workflows/template-build.yml, build-scripts/create-commits-history.ps1, build-scripts/update-rule-history.ps1
=> 🐛 Fix optional history bug + add more logs

build-scripts/test.ps1, build-scripts/update-rule-history.ps1
=> handle null created date

README.md
As per my conversation with @bradystroud, I have added a section named "Example Rule" in the ReadMe.
=> Update README.md to add Example Rule section

src/style.css, tailwind.config.js
@jeoffreyfischer 
This is to replace the script created on https://github.com/SSWConsulting/SSW.Rules/pull/1407/files
Relates to https://github.com/SSWConsulting/SSW.Rules/issues/1397
=> Update style.css to fix boxes

src/style.css
cc @jeoffreyfischer 
Relates to https://github.com/SSWConsulting/SSW.Rules/issues/1397
=> Fixing boxes with lists and multiple elements inside

site-config.js
cc @wicksipedia 
as per @adamcogan 's email: **SSW.Rules | “Star us”**
=> Added extra words to SSW.Rules title

src/style.css, src/templates/rule.js
=> Making "see history" show always in 1 line

package.json, yarn.lock
I've updated the megamenu package to the latest version. This change adds the new hover animation for links to the navbar.
**Figure**: **Testing new hover animation on Rules in staging**
<br>
**Figure**: **Testing mobile search bar on SSW Rules**
=> 💄Megamenu - updated package

package.json, yarn.lock
Relates to #1438
Updated ssw.rules.widget package to 2.0.5 version
=> ♻️ Updated widget package to new version

README.md
As per my conversation with @tiagov8, one of the link was broken because the brackets in the [name](url were wrongly typed
=> 📝 README - fixed broken link

_docs/Definition-of-Done.md
=> Update Definition of Done

.github/workflows/build-deploy-tina-migration.yml, .github/workflows/template-build.yml, .github/workflows/template-deploy.yml, infra/main.bicep
Relates to #1506 
This adds a new GitHub workflow for uploading build artifacts to blob storage. It shares the same build and deploy templates as the staging and production workflows but in a different environment.
**Note**: I haven't created
=> 🚀 CI/CD - Added new workflow for building tina migration branch

README.md
Relates to #1488 
Updates the Definition of Done for the TinaCMS migration project
=> 📄 Update Definition of Done for TinaCMS Migration

.github/workflows/template-build.yml
=> Remove cache for Tina Migration only

.env.template_tina, .github/workflows/template-build.yml, tina/config.ts
Adds .env variable to update TinaCMS Branch used.
=> ♻️ Use .env for TinaCMS Branch

.github/workflows/template-build.yml
Missed to update workflow with the new secrets in this PR #1579, so I have added them here
=> 📝 Added missing secrets to workflow

src/components/footer/footer.js
As per designers request, they don't want the Llama
@tiagov8
Relates to #1425
=> Footer - remove llama emoji

src/hooks/useAppInsights.js
Relates to #1589
This PR adds small change to google analytics logs that was added here https://github.com/SSWConsulting/SSW.Rules/pull/1593
- Added another condition to check this URL also `www.google-analytics.com` to fix analytics errors in Application Insights
=> 🔁 App Insights - Refactored google analytics logs

gatsby-browser.js, package.json, src/style.css, yarn.lock
Relates to #1600
Change font family from "Open Sans" to "Inter"
=> ♻️ Changed font family from "Open Sans" to "Inter"

package.json, yarn.lock
Relates to https://github.com/SSWConsulting/SSW.Website/issues/3449
This PR updates the megamenu to the latest version (i.e. the version that supports thumbnails next to sidebar headings
**Figure**: **Updated sidebar heading**
=> updated megamenu to the latest version

package.json, yarn.lock
=> 🔥Hotfix - release megamenu icon #733

infra/main.bicep, src/components/discussion/discussion.js
Relates to https://github.com/SSWConsulting/SSW.Rules.Content/issues/9987
=> Added giscus origin

README.md
Updated the content branch name mentioned in the README to reduce confusion
=> 📝 Update README to reflect correct content branch

package.json, yarn.lock
Relates to https://github.com/SSWConsulting/SSW.Website/issues/3971
=> ⬆️Bumped megamenu to 4.12.0
