SSWConsulting/SSW.Rules

src/style.css

https://github.com/SSWConsulting/SSW.Rules/issues/267
Long figure statements, links, paths and greyboxes were causing the rules page to overflow.

💄  Add word break to rule content

---

src/style.css

So it underlines for SSW Rules too

included <a> breadcrumb in the CSS

---

src/style.css

Improving mobile view of email templates

---

static/admin/index.html

https://www.freecodecamp.org/news/how-to-build-a-blog-with-gatsby-and-netlify-cms/
https://www.netlifycms.org/docs/add-to-your-site/
Both these links say you should add an index.html even though it works locally without.
I am hoping this will make it work on staging

Add netlify cms index

---

src/style.css

This is to avoid overflow https://www.ssw.com.au/rules/use-open-graph

boxes from display table to block

---

src/templates/rule.js

Reverts SSWConsulting/SSW.Rules#507 as it may be causing this bug.
This is only happening when you load a rule via the link, not through a category

Revert "Make next and previous buttons always show up"

---

src/templates/rule.js

issue #524
This change makes it check if the related URI on rule is one of the redirects on another rule.
If rule A has rule B listed as related and rule B changes its URI (and adds old URI to redirects list), the related section on rule A wouldn't work. 
Now, when rule A loads its related rules, it will check in the redirects list of rule B.

Check if the related URI is in the redirects list

---

static/admin/config.yml

Issue #557
This config option will give all users the open authoring editorial workflow and force them to fork the repo instead of branching.

🚸  Enable always_fork config option

---

gatsby-config.js

issue #565 
**Figure: Fixed - the YouTube video frame is now the same size as the thumbnails**

UI - Fix youtube embed frame size

---

src/cms/previewTemplate.js
src/components/breadcrumb/breadcrumb.js
src/helpers/convertUrlFromString.js
src/templates/rule.js

This fixes issue [#414](https://github.com/SSWConsulting/SSW.Rules/issues/414) and PBI [60653](https://dev.azure.com/ssw/SSW.Rules/_workitems/edit/60653).
Links included in the 'archived reason' field of a rule are now clickable.
**Figure: Link is now a clickable \<a\> tag**

Make links in archived reason clickable

---

lib/ssw.megamenu/menu/menu.module.css
src/style.css

Closes issue #384 and PBI [60420](https://dev.azure.com/ssw/SSW.Rules/_workitems/edit/60420)
Added styling for header elements (logo, buttons, navbar and breadcrumb) to create breathing room on the left and right for smaller screens.
**Figure: Mobile screen with breathing room**

💄 Add breathing room for mobile screens

---

lib/ssw.megamenu/menu/menu.module.css
src/style.css

As per the conversation with @bradystroud @adamcogan, the breadcrumb was realigned to line up with the menu above it.
**Figure: Breadcrumb icon now lines up with hamburger icon above.**

Updated breadcrumb responsive behaviour to align with menu above.

---

src/style.css

Closes issue #417 and PBI 60656.
Added styling for a CodeAuditor box to be used with Markdown. Also restyled the Info and China boxes to have nicer padding and centring. 
Figure: CodeAuditor box used in a test rule.

Added the CodeAuditor Box

---

src/components/header/header.js
src/style.css
src/templates/category.js
src/templates/rule.js

Closes issue #572  and PBI 62186.
Added an 'Edit in GitHub' button to the rule template, and changed the existing UI to suit.
Figure: Edit button moved in a category.
Figure: Edit button moved in a rule and new button added.

Add advanced edit button

---

src/components/footer/footer.js
src/components/header/header.js
src/style.css

Closes issue #620 and PBI 63218.
Added a 'help' button to the header of SSW Rules and moved info button to footer as a link.
**Figure: Help button in the header where Info button was.**
**Figure: Info button link is now in footer.**

63218 help button

---

src/style.css

Closes issue #627 and PBI 63292
Make links within headings red instead of black.
**Figure: Headings now red even though they are links**

Make heading links red

---

src/cms/config.js

Closes issue #607 and PBI 62890
Removes validation from the redirect URI to allow special characters to be used. This allows old URIs with parentheses, apostrophes and other characters to be stored for redirection, but doesn't allow new URIs to feature these characters.
**Figure: Saved redirect URI with special characters**

Remove validation from redirect URI

---

src/cms/config.js

Added text to the default value of the Body field in the editor to provide users with some instructions when creating a new rule.

Add instructions to new rule default text

---

src/style.css

The original change in #630 that resolved #627 was incorrectly scoped and affected rule headings as well as headings within the content itself.
**Figure: Rule headers changed to red accidentally**
This has been amended in this PR.
**Figure: Rule headers now original black colour**

Fix - Make heading links red

---

src/components/bookmark/bookmark.js
src/style.css
src/templates/category.js

Closes #241 and PBI 59813
Added 'bookmark', 'edit' and 'edit in GitHub' buttons next to rules on the category page.
**Figure: Buttons added to header of a rule on category page**

 Add editing buttons to rules on category page

---

src/style.css

Improving and simplifying footer links

---

src/style.css
src/templates/category.js

Fixes UI bugs introduced in #630 and #648
**Figure: Category heading not centred vertically**
**Figure: Now centred**
**Figure: This is a link, but there is no styling to show that**
**Figure: Link is now clearly visible as it originally was**

Fixing links

---

src/components/profile-content/profile-content.js
src/templates/category.js

Closes #443 and PBI 60887
Simplified the 'read more' link to save room and avoid repeating the title on the screen. The title is still included in the title / hover text for Google juice.
**Figure: Link simplified with hover text added**

Simplify 'Read More' link

---

.azure/codeauditor-pipeline.yml
.azure/production-pipelines.yml

Closes #651 and PBI 63562
Removes CodeAuditor step from the build pipeline and sets the permanent schedule of the new scheduled CodeAuditor pipeline.
CodeAuditor tests will run every Monday at 12am (2pm Sunday UTC time).

Finalise CodeAuditor pipeline

---

gatsby-config.js

Closes #645 and PBI 63492
Updated max width of images in Gatsby to make images the same width as the content container.
**Figure: Image is now the same width as email template**

Changed image max width to match container size

---

src/cms/config.js

Remove capital letters from URI validation pattern and related rule pattern

Updating validation gatsby config to not include capitals

---

src/style.css

(Checked by Jack)
Cc: @JackDevAU @pierssinclairssw @bradystroud @tiagov8
This PR addresses Issue #706 where images would be stretched beyond their normal dimensions by inline CSS set by Gatsby plugins. 
Changes:
- Update the Site.css for the .rules-content img with `width: auto !important;`
**Figure: Showing the updated CSS and the fixed image.**
**Note:** I was unable to replicate the vertical stretching with the second image (QR Code). In the case this PR doesn't fix that issue I will investigate further.

🐛 Fix image stretching horizontally issue

---

src/components/all-rules-content/allRulesContent.js
src/helpers/sanitizeName.js
src/pages/all-rules.js
src/pages/index.js

#711 
Fixed the "All Rules" button URL - (This was incorrectly linking you to `/rules/rules/all-rules`
**Figure: The All Rules button taking you to the wrong URL**

🐛 Fix the all rules button linking to the url

---

src/components/all-rules-content/allRulesContent.js

#711
Fixed the Rules URLs - (These were incorrectly linking you to `/rules/rules/<rule-uri>`)
Figure: The Rules URL

🐛 Remove the extra /rules infront of the links

---

lib/ssw.megamenu/menu/menu.module.css

Cc: @JackDevAU @bradystroud 
As per the issue from @tiagov8 
https://github.com/SSWConsulting/SSW.Rules/issues/762
Changes:
- Update the Menu module css to make the content 100% width

🐛 Have the MegaMenu content at 100% width

---

gatsby-config.js
package.json
yarn.lock

#701 [#1801](https://github.com/SSWConsulting/SSW.Rules.Content/issues/1801)
- Added a Gatsby plugin that adds anchor tags to all `h3` elements.
**Figure: shareable/linkable headings**

✨ Add anchor tags to all h3s

---

gatsby-node.js
src/helpers/historyFeedGenerator.js

Cc: @christianmorfordwaitessw @JackDevAU @bradystroud @pierssinclairssw 
No issue - This PR aims to provide a cleaner and faster way to serve our History data to the Rules.Widget
Changes:
- Adding functionality to the onPostBuild for Gatsby to compile a history-feed.json for the Rules Widget to point to

Serve history feed

---

src/style.css

cc @hashemelhossainissw
Example: https://www.ssw.com.au/rules/ppt-test-please
The image is showing a white separator because the bg is white and the border is #eee 
Added CSS to make background the same color as the border, so transparent images look good.

Fixing background for transparent images

---

src/style.css

Fixed as per https://tailwindcss.com/docs/preflight#border-styles-are-reset-globally
When pasting on Outlook content got borders because of Tailwind reset

Fixing borders on paste to Outlook

---

src/components/header/header.js

The word "Rules" on the header is currently linking to ssw.com.au. It should be the Rules homepage

Make "Rules" link to rules site

---

src/style.css

SSW logo and the word Rules is miss-aligned on header. Removed margin top to fix this

Header - Align SSW Logo with word Rules

---

src/components/footer/footer.js

As per CodeAuditor: [URLs - must not include full stop or slash at the end](https://codeauditor.com/htmlhint/2707796e-dc8d-469c-7317-a71b7fa04f98?displayMode=1)

removed slashes from URLs

---

src/style.css

adding a top and bottom margin to the "not-found-greybox" class so that the spacing of the rules 404 page is consistent with the other 404 pages on People and the website.
**Figure: current rules 404 page**
**Figure:Peoples 404 page**

Adding margin to the 404 page specific class

---

src/style.css

This is to solve the problem of having no space after a table:
E.g. https://ssw.com.au/rules/different-types-of-testing

Give margin to tables

---

src/style.css
src/templates/category.js

CC: @adamcogan 
As per an email task from @adamcogan, the content was too thin to read on smaller screens. This PR fixes this by spanning the content the full screen width on smaller devices.
**Figure: Content spans full screen when on small width**

items span full screen when on small screen

---

src/style.css

cc @jaydenalchin 
Made blockquotes :before " only show in the 1st paragraph
Example rule of what I want to fix: https://ssw.com.au/rules/fix-problems-quickly/ 
Related Issue: https://github.com/SSWConsulting/SSW.Rules/issues/844

Made blockquotes :before " only show in the 1st paragraph

---

src/components/breadcrumb/breadcrumb.css
src/components/breadcrumb/breadcrumb.js
src/components/filter/filter.js
src/pages/index.js

- Added underline to clickable breadcrumbs
- Added underline to “Latest Rules”, “Orphaned rules”, “Archived rules”, and  “Unmigrated rules” buttons
- Changed default sorting option to “Recently Updated”

changed all-rules defaults

---

.azure/templates/build.yml
.github/workflows/pr-lint-code.yml
src/pages/index.js

Move PR linting to GitHub action
Benifits of this
- Seperate from build
- Can see the error without going to DevOps
- Simplifies overall architecture
https://github.com/SSWConsulting/SSW.Rules/issues/993
Tested on my fork

🔨 Move lint to GitHub action

---

gatsby-node.js
src/templates/category.js

Added call to action at the bottom of category pages.
This can now be edited through GitHub by adding the following fields to a category md file.
```md
experts: https://www.ssw.com.au/people/?skill={{skill}}
consulting: https://www.ssw.com.au/consulting/{{consulting-page}}
```
The following documentation has been updated to include the new fields:
https://github.com/SSWConsulting/SSW.Rules.Content/wiki/How-to-Add-and-Edit-Categories-and-Top-Categories
**Figure: New call to action at bottom of page**

Added call to action at the bottom of categories

---

src/components/profile-content/profile-content.js
src/pages/orphaned.js
src/templates/category.js

Fixes https://github.com/SSWConsulting/SSW.Rules/issues/956#issuecomment-1571200634
Fixes #987 
- Updated spacing style for Call to Action section
- Changed from "Show Blurb" to "Show blurb"
**Before change:**
**After change:**

💄956 Update style for call to action

---

src/pages/orphaned.js
src/templates/category.js
src/templates/rule.js

Added warning to edit tooltip due to Netlify issues
Related to #1003 
**Figure: New tooltip message**

Added warning to edit tooltip due to Netlify issues

---

src/images/bookmarkIcon.svg
src/images/gavel.svg

This fixes the error "Tags - Id attributes must be unique" as the same SVG would occur multiple times on the same page leading to a "non-unique ID"
Changes:
```
❯ git diff
diff --git a/src/images/bookmarkIcon.svg b/src/images/bookmarkIcon.svg
index 2beedea..0be3bb9 100644
--- a/src/images/bookmarkIcon.svg
+++ b/src/images/bookmarkIcon.svg
@@ -1,10 +1,10 @@
<?xml version="1.0" encoding="UTF-8"?>
<svg width="60px" height="100px" viewBox="0 0 60 100" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
-    <g id="Welcome" stroke="none" stroke-width="1" fill="currentColor" fill-rule="evenodd">
-        <g id="Bookmark2" transform="translate(-1173.000000, -107.000000)" fill="currentColor">
-            <g id="Rectangle" transform="translate(1173.000000, …
```

Removed ID tag from SVG images

---

src/components/header/header.js

Rules header is now clickable and will navigate to rules homepage
Related #504

Added way to navigate to rules homepage via header logo

---

gatsby-config.js
src/components/search-bar/search-bar.js
src/pages/latest-rules.js

Relates to https://github.com/SSWConsulting/SSW.Rules/issues/1033
The search feature is currently making the page render slow because the Markdown data is too large in both staging and production. To solve this, we are trying the use of [Local Search - Lazy-loading the index and store](https://www.gatsbyjs.com/plugins/gatsby-plugin-local-search/#lazy-loading-the-index-andor-store) to reduce the time it takes to fetch the data.
Changes:
- Added lazy-loading for the seach component
- Made the search bar visible only after the data is fetched
- Added application insights

🔎 Optimize Search by Lazy-loading

---

src/style.css

When using an `ol` nested under a `ul`, it gets a combination of the styling for both. This PR fixes the styling by requiring that an `li` is a direct child of a `ul` to receive a bullet
**Figure: Before - `ol` has a mixture of number and bullet**
**Figure: After - `ol` only has a number**

🐛Fix styling for ol nested under ul

---

src/components/search-bar/search-bar.js
src/pages/search.js

Relates to https://github.com/SSWConsulting/SSW.Rules/issues/1033
The link to the search is missing a path prefix "/rules/", which needs to be added in staging and production to ensure that we can access the search page.
Changes:
- Added "/rules/" based on the node environment variables

🐛Fix search relative path

---

src/components/header/header.js
src/pages/latest-rules.js
src/style.css
src/templates/category.js

Relates to #1070 
Changes:
- Made logo text "Rules" a `div`
- Changed category title to `h1`
- Made "Latest Rules" title a `h1`
**Figure: The UI is the same before and after the changes😉**

💄Fix Heading Tag

---

src/components/header/header.js

Removed the slash at end of RulesGPT link that was violating https://ssw.com.au/rules/no-full-stop-or-slash-at-the-end-of-urls/

Removed slash at end of RulesGPT link

---

src/helpers/algolia-queries.js

Added `contentDigest` field as per https://github.com/algolia/gatsby-plugin-algolia#partial-updates
Relates to build issues happening on prod

Added contentDigest field 

---

src/helpers/algolia-queries.js

Hopefully fixes the below issue by adding an `internal` object with `contentDigest` as a param. 
```
error the objects must have internal.contentDigest. Current object:
{
"objectID": "47dcddc2-65bd-5c02-b04b-f6f3cf324cb7",
"title": "Do you avoid changing the URL on a 404 error?",
"slug": "/rules/404-error-avoid-changing-the-url/rule/",
"contentDigest": "dae846231767afd7b132d5db7147224d",
"excerpt": "When you request a URL of a file that doesn't exist, you will get an error message. You should make sure that the URL in the browser doesn't change. This way, it's easy for the user to correct.  E.g. The user doesn't have to retype the whole URL if there is a spelling mistake or a forgotten/mixed up letter."
}
```
Relates to https://github.com/SSWConsulting/SSW.Rules/issues/1102

add correct digest path

---

gatsby-node.js

Updated gatsby-node config to only process MD files that have 'rule' set as it's type within the front-matter.
Relates to #1110

gatsby-node now only processes md files that have 'rule' as it's type

---

.azure/scripts/update-latest-rules.ps1
.azure/update-rule-history.yml
gatsby-node.js

Relates to https://github.com/SSWConsulting/SSW.Rules/issues/1152 & https://github.com/SSWConsulting/SSW.Rules/issues/1171#issuecomment-1849154265
- Adds a new .ps1 script to the pipeline to update the Latest Rules Table 
- Hopefully fixes the metadata issue. Stopped using `pathPrefix` from `site-config.js` for `file` var as it didn't match the gatsby graphql query 
Not sure where to add `$UpdateLatestRulesFunctionKey`

Add UpdateLatest rules to the pipeline 

---

package.json
src/components/latest-rules-content/latestRulesContent.js
src/pages/user/index.js
yarn.lock

Relates to #1231
Changes:
- Upgraded Widget to the latest (with increased font size)
- Changed Heading from "Last Modified" to "Last Modified (13)"

💄 Improve UI of Users' Rule Page

---

gatsby-config.js

Relates to #1172 
**Note: The use of double quotes is necessary as mentioned in this PR: https://github.com/borgfriend/gatsby-remark-embed-video/pull/181**
Fixes this error message: `Uncaught DOMException: Failed to construct 'PresentationRequest': The document is sandboxed and lacks the 'allow-presentation' flag.`

🐛 Fix Sandbox Error

---

.azure/templates/build.yml

Relates to #1216 
Fixed the cache path for yarn packages to prevent Gatsby from deleting all saved pages.

👷 Improve Build Time - Fixed Yarn Cache Path

---

.github/workflows/template-deploy.yml

Relates to https://github.com/SSWConsulting/SSW.Rules/issues/1301
set permission with `id-token:write` at workflow level to fix this error:

Deploy Infra - Add workflow permission

---

gatsby-node.js
src/cms/config.js
src/components/head/head.js
src/components/layout/layout.js
src/helpers/wrapPageElement.js
src/templates/rule.js

Relates to #1305 
Changes:
- Using our custom description when generating pages if a description is present in the frontmatter
- Including a description field in the CMS editor
**Figure: The rule's page using custom description**
**Figure: New description field in the CMS editor**

🔍 SEO - Add Meta Description

---

.github/workflows/build-deploy-production.yml
build-scripts/update-rule-history.ps1

Fixed issue where deploy script did not generate urls correctly - previous implementation assumed that base url would have trailing slash
Fixes #1335 
Figure: Error when running script

Fix rules history script

---

.github/workflows/template-build.yml

Relates to #1337
Added timeout (60 mins) to the action step.

💚GitHub Action - Set Timeout for Build

---

site-config.js
src/components/head/head.js
src/components/layout/layout.js
src/helpers/config/pageTitles.js
src/helpers/wrapPageElement.js

Relates to #1333 
This PR fixes the issue where the default `<title>` in the page source was incorrect for some pages.
**Figure: Orphaned Rule**
**Figure: Homepage**

🐛 Fix Incorrect Default Title in Page Source

---

src/components/layout/layout.js
src/components/signin/signin.js
src/services/authService.js

Relates to Email: SSW Rules has this auth pop up ⚠️
Changes:
- Removed alert and `loginWithRedirect`
- Log users out when both the refresh token and ID token have expired

🐛 Fix Auth Pop-Up When Refresh Token Expires

---

.azure/scripts/update-rule-history.ps1
.github/workflows/build-deploy-production.yml
.github/workflows/build-deploy-staging.yml
.github/workflows/template-build.yml

Relates to #1367
Sometimes there are huge automated changes to lots of rules, we dont want these in the history.
This option allows them to be skipped.

👷 CI/CD - Make commit history update  optional

---

build-scripts/update-rule-history.ps1

`$SkipGenerateHistory` variable wasn't defined, and it was used in `update-rule-history.ps1` file to generate history under `true` condition. Replaced this variable with $ShouldGenerateHistory which is set `true` by default
The updated date data was incorrect on Latest Rules page
Relates to #1390

🐛 Fix Updated Date bug

---

.github/workflows/build-deploy-production.yml
.github/workflows/build-deploy-staging.yml

Allow builds to always run, then wait to deploy until the previous run is finished. This saves time as build takes ~10 minutes, which can be done by the time the previous run finishes deploying

♻️ Allow concurrent builds, but not deploys

---

tailwind.config.js

As per the email:
**From**: @bettybondoc 
**Sent**: Friday, August 2, 2024 9:14 AM
**To**: @jeoffreyfischer 
**Cc**: @jaydenalchin @tiagov8 
**Subject:** SSW.Rules - Fix emphasised heading format
**Description**
The new feature that turns text red when using a strong tag inside a heading is not working as expected.
It does also change the text font weight to bold.
**Expected behaviour**
We want the test font weight to remain semi-bold.
**Solution**
✅ This has been fixed - the text inside a strong tag is now semi-bold (see screenshot).
Relates to #1399
**Screenshot**
**Figure: Example of how strong tag looks in a heading**

💄 Heading strong tag - Keep font width semibold

---

README.md

In the PR #1407 I updated the command to run the project from `yarn develop` to `yarn dev`
However I forgot to update the ReadMe to reflect this change.
The current PR fixes this mistake.

🗒️ ReadMe - Updated "yarn develop" command

---

README.md

**Description**
When working on SSW.Rules, I wanted to edit a rule in order to add a specific markdown implementation.
As per my conversation with @bradystroud, he told me that I could use the `sample-content` branch.
As this use case was not documented, I decided to add a section in the README

🗒️ README - Updating and Syncing a Rule from Rules.Content

---

src/style.css

as per @adamcogan 's **RE: Expenses - Do you track your recurring expenses? | SSW.Rules**\
cc @jeoffreyfischer 
--
**❌ Figure: Extra space on iOS**
**❌ Figure: Lack of space if 1 line only**

Fixed boxes with icons for iOS + for 1 line sentences

---

src/style.css

Fixes this:
https://www.ssw.com.au/rules/craft-and-deliver-engaging-presentations/

Update style.css avoid odd spaces on lists inside boxes

---

.github/workflows/build-deploy-tina-migration.yml
.github/workflows/template-build.yml

This PR updates the staging environment for the tina migration to use the existing staging environment variables.
Because the blob storage account is already being named using a parameter in template-build action
Relates to #1506

Tina Migration - Fix staging environment 

---

.github/workflows/template-build.yml
tina/config.ts

Relates to #1461 
Relates to #1465 
Updates the basePath for Tina so that we can grab the proper resources when hitting /admin.
Make basePath configurable in .env for the future.
_**Figure: /admin is now available on the staging server**_

✨ TinaCMS | Configure Base Path - /admin

---

gatsby-node.js

cc: @bradystroud @Calinator444 @tkapa @BrookJeynes 
Relates to #1448
Added logic to `gatsby-node.js` to remove whitespace from lines that contains only whitespace.
Then tested `yarn build` with new logic and without it.
For testing created `test-sample-content` branch in content repo, and added intentional whitespace to the rule.
**Figure: Line 67 contains a whitespace**
As result:
- ✅ build is successful with new logic
- ❌ build fails without new logic, and the error message was same that we have seen in recent workflow failures.
**Figure: Build fails without new logic**
--- 
🤖 Copilot's summary
This pull request includes changes to the `gatsby-node.js` file to improve the handling of Markdown content and streamline the code.
Content handling improvements:
* …

💡 Added logic to remove whitespace from the line

---

.github/workflows/template-deploy.yml

cc: @tkapa @bradystroud 
After creating a new `release/141` from main, the `Deploy Infra` job was failing due to recent changes into main to support tina migration. 
This pull request includes a small change to the `.github/workflows/template-deploy.yml` file.
**Note:** I will be deleting new created release branch for now.
* `.github/workflows/template-deploy.yml`: Renamed `storageAccountName` to `customStorageAccountNames` in the deployment script so it matches with the `main.bicep` params list.
**Figure: Deploy Infra failing - https://github.com/SSWConsulting/SSW.Rules/actions/runs/11231860515/job/31223250760**

♻️ Renamed storage account param name to match with the bicep param

---

tina/collections/sidebar.ts

Preview images must be prefixed with their base path.
I've created a new Issue in TinaCMS below.
https://github.com/tinacms/tinacms/issues/5203

♻️ Preview Images broken on Staging

---

src/style.css

Update style.css - More space between icon and text on boxes + figures

---

src/hooks/useAppInsights.js

Relates to #1589
This pull request includes a small change to the `useAppInsights` hook. The change ensures that Google Analytics logs with a response code of 0 are marked as success. The reason I explained in this comment https://github.com/SSWConsulting/SSW.Rules/issues/1589#issuecomment-2437107468

🔁 App Insights - Added filter to filter out google analytics with 0 code

---

src/components/comments/comments.js
src/components/discussion/discussion.js
src/style.css

Relates to #1567
Added header to Giscus and Disqus comment box, so both comment system can easily be distinguished and people can copy their old comments to new commenting system which is Giscus 
**Figure: Giscus and Disqus have header**

♻️ Added comments headers

---

src/components/discussion/discussion.js

Relates to #1567
Changed the comment box position to the top, so users don't need scroll all the way down to add a comment when the discussion has many comments
**Figure: Comment box is placed on top of comments**

♻️ Changed the comment box position from bottom to top

---

src/pages/index.js
src/pages/orphaned.js

Google was appending rule lists on `/rules` and `/rules/orphaned` to the snippets for those pages so I've added the data-nosnippet header to ensure the content of these lists will be ignored
For more information about the data-nosnippet attribute see this documentation
https://developers.google.com/search/docs/crawling-indexing/robots-meta-tag#data-nosnippet-attr
**Figure**: **Rule list being used for snippet on rules home page google search result**
**Figure** **rule list being used for snippet on orphaned page google search result**
**Figure**: **Rules category box  with data-nosnippet attribute added**
**Figure**: **Orphaned Rules list has data-nosnippet attirbute added**

Add nosnippet rule categories

---

gatsby-browser.js
gatsby-ssr.js
package.json
src/style.css
yarn.lock

Relates to #1600
This pull request includes updates to replace the `@fontsource/inter` package with `@fontsource-variable/inter`.
`@fontsource-variable/inter` version enables to use single font file that contains multiple variations of the same font, such as different weights, widths, and styles. Read more at docs - https://fontsource.org/docs/getting-started/variable
Also added `preload` option to improve performance by loading font file before they are acquired.
https://fontsource.org/docs/getting-started/preload
https://web.dev/articles/codelab-preload-web-fonts
**Figure: preload link was added to header**
Font updates:
* `gatsby-browser.js`: Replaced `@fontsource/inter` with `@fontsource-variable/inter`.
* `gatsby-ssr.js`: Added import for `@fontsource-variable/inter` and included a …

♻️ Inter Font - Added preload to avoid FOUT issues

---

site-config.js
src/components/layout/layout.js

I've added a meta description to the home page. Since the meta-data gets injected at build time I needed to modify the Layout component with custom logic to update the home page meta description based on the route. It also doesn't appear to be possible to pass the page query data to gatsby-browser.js without opting the page out of static rendering.
~~Also every time I solve a problem using regex pattern a puppy somewhere in the world passes away~~
I've had the new meta-description test passed by Stef

🔍 Added unique meta description for home page

---

gatsby-config.js
package.json
yarn.lock

Relates to #1637
Email: Images should show offline | SSW.Rules
This pull request includes the addition of the `gatsby-plugin-offline` plugin to support "airplane/offline mode"
[Official Docs](https://www.gatsbyjs.com/plugins/gatsby-plugin-offline/)
[Watch local testing video](https://sswcom-my.sharepoint.com/:v:/g/personal/babakamyljanov_ssw_com_au/EfiS8HUwVNFAr--kC-vs7sgBZ_quEROaDHxoTU-1zkN6qA?e=L6DIZf&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D)
I would need to test this in staging as well

✨ Added offline support to Gatsby

---

README.md

Related to #1337
Add documentation for Gatsby build timeout in `README.md`.
* Add a section to document the 30-minute timeout for the Gatsby build step.
* Include a note about the intermittent issues with external dependencies causing delays.
* Provide a link to the Gatsby issue created for tracking the problem.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/SSWConsulting/SSW.Rules/pull/1654?shareId=974a7d8f-4121-4298-81ad-d6c02b0ae854).

Readme - document Gatsby build timeout 

---

gatsby-node.js
site-config.js
src/components/dropdown-card/dropdown-card.js
src/components/dropdown-icon/dropdown-icon.js
src/components/footer/footer.js
src/components/profile-content/profile-content.js
src/components/profile-filter-menu/profile-filter-menu.js
src/pages/profile.js
src/style.css

Relates to #1580 
- Added Profile page with Bookmarks tab
**Figure: Link to User profile page**
**Figure: Bookmarks tab**
**Figure: Mobile view**

✨ Added Profile page with Bookmarks

---

src/components/contact-info/contact-info.js
src/components/side-bar/side-bar.js

cc @jaydenalchin @bettybondoc @adamcogan 
FROM
TO

Improved sidebar heading look and feel

---

src/pages/user/index.js

cc: @Freego1783 
Email: "Re: SSW Rules - Searching by author - Nothing showing for me"
Rules weren't being displayed for Hugo on search page. The reason is when rule is created, the markdown file name was "rules.md", and then it was changed to "rule.md". Current logic for that page only removes "rule.md" from path and it doesn't work for "rules.md".
So I've created function that retrieves path without filename.
**Figure: Hugo's rule is displayed on Acknowledged section**

Fixed acknowledged rules

---

.github/workflows/pr-build.yml
.github/workflows/template-build.yml
build-scripts/update-rule-history.ps1

I merged the very large PR into the content repo and that broke the history generation scripts. They are supposed to skip giant PRs but the skin functionally wasn't working, so I fixed it in this PR.
https://github.com/SSWConsulting/SSW.Rules.Content/pull/9882

CI/CD - Fix builds from big content change

---

src/components/discussion/discussion.js
src/style.css
static/giscus-theme.css

Relates to #https://github.com/SSWConsulting/SSW.Rules.Content/issues/9987
- Added custom theme file to repo which hides upvote button.
- Serve theme file using https://statically.io/convert/
- Added TODO comment to clean up this after GitHub fixes issue

Hide upvote button from Giscus discussion

---

.github/workflows/template-build.yml
README.md

Looking at the history it never goes longer than 30 min. This reduces wasted action minutes but doesn't fix the problem - we have no idea why its failing 
https://github.com/SSWConsulting/SSW.Rules/issues/1337

Build action - change timeout from 1hr to 30min

---

src/pages/user/index.js

Relates to
#1652 
#1361 
Added missing `githubUrl` field to query.

Added missing query field that required to get data

---

src/pages/user/index.js

Relates to #1652
Improved `normalizeName` function to remove any nicknames after fullname for finding acknowledged rules list for user.
For example, JK has different values on author>title frontmatter on rules:
- Jernej Kavka
- Jernej Kavka (JK)

Added extra check to clean-up full name
